# -*- coding: utf-8 -*-
"""ddpm_cifar10_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMESOAvbjosuJlWc2Hfx43voXyI_OVp-

# DDPM on CIFAR-10 — Colab-Ready Pipeline

This notebook is a **single-GPU, Colab-friendly** version of a DDPM training/sampling/evaluation pipeline
(v-prediction, cosine noise schedule, self-conditioning, min-SNR-γ loss weighting, EMA, DDIM sampling).

**What changed from the original multi-GPU scripts:**
- Removed `torch.distributed` / `DDP` / `torchrun` — Colab gives you a single GPU, so the training loop now runs
  as a plain single-process script (same math, same architecture, same loss — just no distributed scaffolding).
- Fixed a bug where the original resume logic pointed at a hardcoded file (`checkpoints/ddpm_epoch_100.pt`).
  It now auto-detects the **latest** checkpoint in your checkpoint folder.
- Added an optional Google Drive mount so checkpoints survive when your Colab runtime disconnects
  (free-tier Colab sessions are capped at ~12 hours, and can disconnect earlier from inactivity).
- Split the original single-file script into `ddpm_model.py` (architecture + sampler) and `ddpm_train.py`
  (training loop), matched by `ddpm_generate.py` and `ddpm_evaluate.py` for sampling/FID.

**Before you start:** In the menu bar go to `Runtime > Change runtime type` and select a **GPU** (T4 is fine).

**A note on scale:** this is the original CIFAR-10 architecture (128–512 channels, attention at 16×16/8×8, batch
size 64) trained for up to 1000 epochs. On a single free-tier T4 this is genuinely a multi-day job. The notebook
is fully resumable — just re-run the training cell after a disconnect and it will pick up from the last saved
checkpoint. If you want faster iteration, lower `--epochs`, `--save_every`, or `--batch_size` in the training cell.

## 1. Install dependencies
"""

!pip install -q torch-fidelity tqdm

import torch
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("No GPU detected — go to Runtime > Change runtime type > GPU before continuing.")

"""## 2. (Optional but recommended) Mount Google Drive

Checkpoints and generated samples can be large and training can take many sessions to finish.
Mounting Drive means your progress survives a Colab disconnect. Skip this cell if you're fine keeping
everything in the ephemeral `/content` runtime disk (you'll lose it when the session ends).
"""

USE_DRIVE = True  # set to False to keep everything local to the Colab runtime

import os

if USE_DRIVE:
    from google.colab import drive
    drive.mount('/content/drive')
    CHECKPOINT_DIR = '/content/drive/MyDrive/ddpm_cifar10/checkpoints'
else:
    CHECKPOINT_DIR = '/content/checkpoints'

os.makedirs(CHECKPOINT_DIR, exist_ok=True)
print("Checkpoints will be saved to:", CHECKPOINT_DIR)

"""## 3. Write the model + sampler module (`ddpm_model.py`)

Architecture, cosine noise schedule, EMA, and the DDIM sampler — unchanged from the original math.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ddpm_model.py
# 
# import os
# import math
# import shutil
# import torch
# import torch.nn as nn
# from torchvision.utils import save_image
# 
# # Environment Setup
# os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
# 
# # =====================================================================
# # 1. CONFIGURATION & HYPERPARAMETERS
# # =====================================================================
# img_size = 32
# T = 1000
# 
# # COSINE NOISE SCHEDULE IMPLEMENTATION
# def get_cosine_schedule(T, s=0.008):
#     steps = T + 1
#     t = torch.linspace(0, T, steps, dtype=torch.float64)
#     alphas_cumprod = torch.cos(((t / T) + s) / (1 + s) * math.pi / 2) ** 2
#     alphas_cumprod = alphas_cumprod / alphas_cumprod[0]
#     betas = 1 - (alphas_cumprod[1:] / alphas_cumprod[:-1])
#     return torch.clip(betas, 0.0001, 0.9999).float()
# 
# # =====================================================================
# # 2. NETWORK MODULES
# # =====================================================================
# class SinusoidalPositionEmbeddings(nn.Module):
#     def __init__(self, dim):
#         super().__init__()
#         self.dim = dim
#     def forward(self, time):
#         device = time.device
#         half_dim = self.dim // 2
#         embeddings = math.log(10000) / (half_dim - 1)
#         embeddings = torch.exp(torch.arange(half_dim, device=device) * -embeddings)
#         embeddings = time[:, None] * embeddings[None, :]
#         embeddings = torch.cat((embeddings.sin(), embeddings.cos()), dim=-1)
#         return embeddings
# 
# class AdaGN(nn.Module):
#     def __init__(self, num_groups, num_channels, time_emb_dim):
#         super().__init__()
#         self.gn = nn.GroupNorm(num_groups, num_channels, eps=1e-5, affine=False)
#         self.fc = nn.Linear(time_emb_dim, num_channels * 2)
#         nn.init.zeros_(self.fc.weight)
#         nn.init.zeros_(self.fc.bias)
# 
#     def forward(self, x, t):
#         emb = self.fc(t)
#         gamma, beta = emb.chunk(2, dim=1)
#         gamma = gamma[(...,) + (None,) * 2]
#         beta = beta[(...,) + (None,) * 2]
#         return self.gn(x) * (1 + gamma) + beta
# 
# class UpgradedPreActBlock(nn.Module):
#     def __init__(self, in_ch, out_ch, time_emb_dim, dropout=0.1):
#         super().__init__()
#         self.adagn1 = AdaGN(32, in_ch, time_emb_dim)
#         self.act1 = nn.GELU()
#         self.conv1 = nn.Conv2d(in_ch, out_ch, 3, padding=1)
#         self.adagn2 = AdaGN(32, out_ch, time_emb_dim)
#         self.act2 = nn.GELU()
#         self.dropout = nn.Dropout(dropout)
#         self.conv2 = nn.Conv2d(out_ch, out_ch, 3, padding=1)
#         nn.init.zeros_(self.conv2.weight); nn.init.zeros_(self.conv2.bias)
#         self.shortcut = nn.Conv2d(in_ch, out_ch, 1) if in_ch != out_ch else nn.Identity()
#     def forward(self, x, t):
#         h = self.act1(self.adagn1(x, t))
#         h = self.conv1(h)
#         h = self.act2(self.adagn2(h, t))
#         h = self.dropout(h)
#         h = self.conv2(h)
#         return h + self.shortcut(x)
# 
# class AttentionBlock(nn.Module):
#     def __init__(self, channels):
#         super().__init__()
#         self.mha = nn.MultiheadAttention(embed_dim=channels, num_heads=4, batch_first=True)
#         self.ln = nn.LayerNorm([channels])
#         self.ff = nn.Sequential(nn.Linear(channels, channels), nn.GELU(), nn.Linear(channels, channels))
#     def forward(self, x):
#         B, C, H, W = x.shape
#         x_flat = x.view(B, C, H * W).permute(0, 2, 1)
#         x_norm = self.ln(x_flat)
#         attn_out, _ = self.mha(x_norm, x_norm, x_norm)
#         attn_out = attn_out + x_flat
#         ff_out = self.ff(self.ln(attn_out)) + attn_out
#         return (ff_out.permute(0, 2, 1).view(B, C, H, W)) + x
# 
# class DDPM(nn.Module):
#     def __init__(self, dropout=0.1):
#         super().__init__()
# 
#         time_dim = 512
# 
#         self.time_mlp = nn.Sequential(
#             SinusoidalPositionEmbeddings(time_dim),
#             nn.Linear(time_dim, time_dim),
#             nn.GELU(),
#         )
# 
#         self.inc = nn.Conv2d(6, 128, 3, padding=1)
# 
#         # 32x32 (No Attention)
#         self.down1_b1 = UpgradedPreActBlock(128, 128, time_dim, dropout)
#         self.down1_b2 = UpgradedPreActBlock(128, 128, time_dim, dropout)
#         self.down1_b3 = UpgradedPreActBlock(128, 128, time_dim, dropout)
#         self.down1_b4 = UpgradedPreActBlock(128, 128, time_dim, dropout)
#         self.down1_down = nn.Conv2d(128, 256, 3, stride=2, padding=1)
# 
#         # 16x16
#         self.down2_b1 = UpgradedPreActBlock(256, 256, time_dim, dropout)
#         self.down2_b2 = UpgradedPreActBlock(256, 256, time_dim, dropout)
#         self.down2_b3 = UpgradedPreActBlock(256, 256, time_dim, dropout)
#         self.down2_b4 = UpgradedPreActBlock(256, 256, time_dim, dropout)
#         self.attn16 = AttentionBlock(256)
#         self.down2_down = nn.Conv2d(256, 256, 3, stride=2, padding=1)
# 
#         # 8x8
#         self.down3_b1 = UpgradedPreActBlock(256, 512, time_dim, dropout)
#         self.down3_b2 = UpgradedPreActBlock(512, 512, time_dim, dropout)
#         self.down3_b3 = UpgradedPreActBlock(512, 512, time_dim, dropout)
#         self.down3_b4 = UpgradedPreActBlock(512, 512, time_dim, dropout)
#         self.attn8 = AttentionBlock(512)
#         self.down3_down = nn.Conv2d(512, 512, 3, stride=2, padding=1)
# 
#         # 4x4 Bottleneck
#         self.mid_b1 = UpgradedPreActBlock(512, 512, time_dim, dropout)
#         self.mid_attn = AttentionBlock(512)
#         self.mid_b2 = UpgradedPreActBlock(512, 512, time_dim, dropout)
# 
#         # Up 8x8
#         self.up3_up = nn.Upsample(scale_factor=2, mode="nearest")
#         self.up3_b1 = UpgradedPreActBlock(1024, 512, time_dim, dropout)
#         self.up3_b2 = UpgradedPreActBlock(512, 512, time_dim, dropout)
#         self.up3_b3 = UpgradedPreActBlock(512, 512, time_dim, dropout)
#         self.up3_b4 = UpgradedPreActBlock(512, 256, time_dim, dropout)
#         self.up_attn8 = AttentionBlock(256)
# 
#         # Up 16x16
#         self.up2_up = nn.Upsample(scale_factor=2, mode="nearest")
#         self.up2_b1 = UpgradedPreActBlock(512, 256, time_dim, dropout)
#         self.up2_b2 = UpgradedPreActBlock(256, 256, time_dim, dropout)
#         self.up2_b3 = UpgradedPreActBlock(256, 256, time_dim, dropout)
#         self.up2_b4 = UpgradedPreActBlock(256, 256, time_dim, dropout)
#         self.up_attn16 = AttentionBlock(256)
# 
#         # Up 32x32 (No Attention)
#         self.up1_up = nn.Upsample(scale_factor=2, mode="nearest")
#         self.up1_b1 = UpgradedPreActBlock(384, 128, time_dim, dropout)
#         self.up1_b2 = UpgradedPreActBlock(128, 128, time_dim, dropout)
#         self.up1_b3 = UpgradedPreActBlock(128, 128, time_dim, dropout)
#         self.up1_b4 = UpgradedPreActBlock(128, 128, time_dim, dropout)
# 
#         # Output
#         self.norm_out = nn.GroupNorm(32, 128)
#         self.act_out = nn.GELU()
#         self.outc = nn.Conv2d(128, 3, 3, padding=1)
# 
#     def forward(self, x, t, x_self_cond=None):
#         if x_self_cond is None:
#             x_self_cond = torch.zeros_like(x)
# 
#         x = torch.cat([x, x_self_cond], dim=1)
#         x = self.inc(x)
#         t = self.time_mlp(t)
# 
#         x1 = self.down1_b1(x, t)
#         x1 = self.down1_b2(x1, t)
#         x1 = self.down1_b3(x1, t)
#         x1 = self.down1_b4(x1, t)
#         d1 = self.down1_down(x1)
# 
#         x2 = self.down2_b1(d1, t)
#         x2 = self.down2_b2(x2, t)
#         x2 = self.down2_b3(x2, t)
#         x2 = self.down2_b4(x2, t)
#         x2 = self.attn16(x2)
#         d2 = self.down2_down(x2)
# 
#         x3 = self.down3_b1(d2, t)
#         x3 = self.down3_b2(x3, t)
#         x3 = self.down3_b3(x3, t)
#         x3 = self.down3_b4(x3, t)
#         x3 = self.attn8(x3)
#         d3 = self.down3_down(x3)
# 
#         m = self.mid_b1(d3, t)
#         m = self.mid_attn(m)
#         m = self.mid_b2(m, t)
# 
#         u3 = self.up3_up(m)
#         u3 = torch.cat([u3, x3], dim=1)
#         u3 = self.up3_b1(u3, t)
#         u3 = self.up3_b2(u3, t)
#         u3 = self.up3_b3(u3, t)
#         u3 = self.up3_b4(u3, t)
#         u3 = self.up_attn8(u3)
# 
#         u2 = self.up2_up(u3)
#         u2 = torch.cat([u2, x2], dim=1)
#         u2 = self.up2_b1(u2, t)
#         u2 = self.up2_b2(u2, t)
#         u2 = self.up2_b3(u2, t)
#         u2 = self.up2_b4(u2, t)
#         u2 = self.up_attn16(u2)
# 
#         u1 = self.up1_up(u2)
#         u1 = torch.cat([u1, x1], dim=1)
#         u1 = self.up1_b1(u1, t)
#         u1 = self.up1_b2(u1, t)
#         u1 = self.up1_b3(u1, t)
#         u1 = self.up1_b4(u1, t)
# 
#         return self.outc(self.act_out(self.norm_out(u1)))
# 
# # =====================================================================
# # 3. TRAINING / SAMPLING UTILITIES
# # =====================================================================
# def update_ema(ema_model, model, decay=0.999):
#     raw_model = model.module if hasattr(model, "module") else model
#     with torch.no_grad():
#         for ema_param, param in zip(ema_model.parameters(), raw_model.parameters()):
#             ema_param.data.mul_(decay).add_(param.data, alpha=1.0 - decay)
# 
# def forward_diffusion(x0, t, alpha_bar):
#     noise = torch.randn_like(x0)
#     alpha_hat = alpha_bar[t].view(-1, 1, 1, 1)
#     xt = torch.sqrt(alpha_hat) * x0 + torch.sqrt(1 - alpha_hat) * noise
#     return xt, noise
# 
# @torch.no_grad()
# def generate_fid_samples_ddim(model, alpha_bar, device, total_samples=10000, batch_size=64,
#                                ddim_steps=50, output_dir="fake_images"):
#     model.eval()
#     if os.path.exists(output_dir):
#         shutil.rmtree(output_dir)
#     os.makedirs(output_dir, exist_ok=True)
# 
#     times = torch.linspace(0, T - 1, ddim_steps, dtype=torch.long, device=device)
#     times_prev = torch.cat([torch.tensor([-1], device=device), times[:-1]])
# 
#     img_counter = 0
#     num_batches = math.ceil(total_samples / batch_size)
#     print(f"\n⚡ DDIM Sampler: generating {total_samples} samples over {ddim_steps} steps...", flush=True)
# 
#     use_amp = device.type == "cuda"
#     for b in range(num_batches):
#         current_batch_size = min(batch_size, total_samples - img_counter)
#         x = torch.randn(current_batch_size, 3, img_size, img_size, device=device)
#         x_self_cond = None
# 
#         with torch.amp.autocast("cuda", enabled=use_amp):
#             for idx in reversed(range(ddim_steps)):
#                 t = times[idx]
#                 t_prev = times_prev[idx]
#                 t_batch = torch.full((current_batch_size,), t, device=device, dtype=torch.long)
# 
#                 v_pred = model(x, t_batch, x_self_cond)
# 
#                 alpha_hat = alpha_bar[t]
#                 alpha_hat_prev = alpha_bar[t_prev] if t_prev >= 0 else torch.tensor(1.0, device=device)
# 
#                 pred_x0 = torch.sqrt(alpha_hat) * x - torch.sqrt(1 - alpha_hat) * v_pred
#                 pred_x0 = pred_x0.clamp(-1, 1)
# 
#                 noise_pred = (x - torch.sqrt(alpha_hat) * pred_x0) / torch.sqrt(1 - alpha_hat)
# 
#                 x_self_cond = pred_x0.detach()
# 
#                 dir_xt = torch.sqrt(1 - alpha_hat_prev) * noise_pred
#                 x = torch.sqrt(alpha_hat_prev) * pred_x0 + dir_xt
# 
#         x = ((x + 1) / 2).clamp(0, 1)
#         for i in range(current_batch_size):
#             save_image(x[i].cpu(), f"{output_dir}/fake_{img_counter}.png")
#             img_counter += 1
# 
#     print(f"Images ready in '{output_dir}/'\n", flush=True)
#

"""## 4. Write the training script (`ddpm_train.py`)

Single-GPU training loop with auto-resume from the latest checkpoint found in `CHECKPOINT_DIR`.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ddpm_train.py
# 
# import os
# import re
# import glob
# import copy
# import random
# import argparse
# import torch
# import torch.optim as optim
# from torch.utils.data import DataLoader
# from torchvision import datasets, transforms
# from torchvision.utils import save_image
# 
# try:
#     from tqdm.auto import tqdm
# except ImportError:
#     def tqdm(x, **kwargs):
#         return x
# 
# from ddpm_model import (
#     DDPM, img_size, T, get_cosine_schedule,
#     update_ema, forward_diffusion, generate_fid_samples_ddim
# )
# 
# 
# def find_latest_checkpoint(checkpoint_dir):
#     """Scans checkpoint_dir for ddpm_epoch_*.pt files and returns the one
#     with the highest epoch number (or None if no checkpoints exist)."""
#     ckpts = glob.glob(os.path.join(checkpoint_dir, "ddpm_epoch_*.pt"))
#     if not ckpts:
#         return None
# 
#     def epoch_num(p):
#         m = re.search(r"ddpm_epoch_(\d+)\.pt$", p)
#         return int(m.group(1)) if m else -1
# 
#     return max(ckpts, key=epoch_num)
# 
# 
# def train(epochs=1000, batch_size=64, lr_rate=2e-4, grad_accum_steps=1,
#           checkpoint_dir="checkpoints", data_dir="./data",
#           save_every=50, fid_samples_per_ckpt=64, ddim_steps_eval=500,
#           num_workers=2):
# 
#     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#     if device.type == "cpu":
#         print("No GPU detected. In Colab go to Runtime > Change runtime type > "
#               "GPU (T4). Training on CPU will be extremely slow.")
# 
#     # Noise schedule
#     betas = get_cosine_schedule(T).to(device)
#     alphas = 1.0 - betas
#     alpha_bar = torch.cumprod(alphas, dim=0)
# 
#     # Min-SNR-gamma loss weighting
#     snr = alpha_bar / (1.0 - alpha_bar)
#     SNR_GAMMA = 5.0
# 
#     os.makedirs(checkpoint_dir, exist_ok=True)
#     os.makedirs("real_images", exist_ok=True)
# 
#     transform = transforms.Compose([
#         transforms.RandomHorizontalFlip(),
#         transforms.ToTensor(),
#         transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
#     ])
#     train_dataset = datasets.CIFAR10(root=data_dir, train=True, download=True, transform=transform)
#     train_loader = DataLoader(
#         train_dataset, batch_size=batch_size, shuffle=True,
#         drop_last=True, num_workers=num_workers, pin_memory=True,
#     )
# 
#     # Dump reference real images once (used later for FID comparisons if needed)
#     if len(os.listdir("real_images")) < 10000:
#         real_counter = 0
#         for imgs, _ in train_loader:
#             for img in imgs:
#                 if real_counter >= 10000:
#                     break
#                 save_image((img + 1) / 2, f"real_images/real_{real_counter}.png")
#                 real_counter += 1
#             if real_counter >= 10000:
#                 break
# 
#     model = DDPM().to(device)
#     optimizer = optim.AdamW(model.parameters(), lr=lr_rate, weight_decay=1e-4)
#     scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)
#     scaler = torch.amp.GradScaler("cuda", enabled=(device.type == "cuda"))
# 
#     ema_model = copy.deepcopy(model).to(device)
#     ema_model.eval()
#     for p in ema_model.parameters():
#         p.requires_grad = False
# 
#     # ── Auto-resume: pick up the newest checkpoint found on disk ──────────
#     start_epoch = 0
#     latest_ckpt = find_latest_checkpoint(checkpoint_dir)
#     if latest_ckpt:
#         print(f"\nFound checkpoint! Resuming from {latest_ckpt}...\n")
#         checkpoint = torch.load(latest_ckpt, map_location=device, weights_only=False)
#         model.load_state_dict(checkpoint["model_state_dict"])
#         ema_model.load_state_dict(checkpoint["ema_model_state_dict"])
#         start_epoch = checkpoint["epoch"]
#         for _ in range(start_epoch):
#             scheduler.step()
# 
#     print("\nStarting training loop (single-GPU, mixed precision)...")
# 
#     for epoch in range(start_epoch, epochs):
#         model.train()
#         total_loss = 0.0
#         optimizer.zero_grad()
# 
#         pbar = tqdm(train_loader, desc=f"Epoch {epoch + 1}/{epochs}")
#         for batch_idx, (x, _) in enumerate(pbar):
#             x = x.to(device)
#             t = torch.randint(0, T, (x.shape[0],), device=device)
#             xt, noise = forward_diffusion(x, t, alpha_bar)
# 
#             alpha_hat_t = alpha_bar[t].view(-1, 1, 1, 1)
#             v_target = torch.sqrt(alpha_hat_t) * noise - torch.sqrt(1 - alpha_hat_t) * x
# 
#             # Self-conditioning (50% of steps)
#             x_self_cond = None
#             if random.random() < 0.5:
#                 with torch.no_grad():
#                     with torch.amp.autocast("cuda", enabled=(device.type == "cuda")):
#                         v_pred_sc = model(xt, t)
#                         x_self_cond = (
#                             torch.sqrt(alpha_hat_t) * xt - torch.sqrt(1 - alpha_hat_t) * v_pred_sc
#                         ).clamp(-1, 1).detach()
# 
#             with torch.amp.autocast("cuda", enabled=(device.type == "cuda")):
#                 v_pred = model(xt, t, x_self_cond)
# 
#                 snr_t = snr[t]
#                 weights = torch.minimum(snr_t, snr_t.new_full([], SNR_GAMMA)) / snr_t
#                 weights = weights.view(-1, 1, 1, 1)
#                 loss = (weights * (v_pred - v_target) ** 2).mean()
#                 loss = loss / grad_accum_steps
# 
#             scaler.scale(loss).backward()
# 
#             if (batch_idx + 1) % grad_accum_steps == 0:
#                 scaler.unscale_(optimizer)
#                 torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
#                 scaler.step(optimizer)
#                 scaler.update()
#                 optimizer.zero_grad()
# 
#                 current_decay = 0.9999 if epoch >= 200 else 0.999
#                 update_ema(ema_model, model, decay=current_decay)
# 
#             total_loss += (loss.item() * grad_accum_steps)
#             pbar.set_postfix(loss=total_loss / (batch_idx + 1))
# 
#         scheduler.step()
#         current_lr = optimizer.param_groups[0]["lr"]
#         print(f"Epoch [{epoch + 1}/{epochs}] | Loss: {total_loss / len(train_loader):.6f} | LR: {current_lr:.6f}")
# 
#         if (epoch + 1) % save_every == 0:
#             checkpoint_path = os.path.join(checkpoint_dir, f"ddpm_epoch_{epoch + 1}.pt")
#             torch.save({
#                 "epoch": epoch + 1,
#                 "model_state_dict": model.state_dict(),
#                 "ema_model_state_dict": ema_model.state_dict(),
#             }, checkpoint_path)
#             print(f"Saved checkpoint: {checkpoint_path}")
# 
#             generate_fid_samples_ddim(
#                 model=ema_model,
#                 alpha_bar=alpha_bar,
#                 device=device,
#                 total_samples=fid_samples_per_ckpt,
#                 batch_size=min(64, fid_samples_per_ckpt),
#                 ddim_steps=ddim_steps_eval,
#                 output_dir=f"fake_images_epoch_{epoch + 1}",
#             )
# 
#     print("\nTraining complete.")
# 
# 
# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument("--epochs", type=int, default=1000)
#     parser.add_argument("--batch_size", type=int, default=64)
#     parser.add_argument("--lr", type=float, default=2e-4)
#     parser.add_argument("--grad_accum_steps", type=int, default=1)
#     parser.add_argument("--checkpoint_dir", type=str, default="checkpoints")
#     parser.add_argument("--data_dir", type=str, default="./data")
#     parser.add_argument("--save_every", type=int, default=50)
#     args = parser.parse_args()
# 
#     train(
#         epochs=args.epochs,
#         batch_size=args.batch_size,
#         lr_rate=args.lr,
#         grad_accum_steps=args.grad_accum_steps,
#         checkpoint_dir=args.checkpoint_dir,
#         data_dir=args.data_dir,
#         save_every=args.save_every,
#     )
#


"""

!python ddpm_train.py \
    --epochs 1000 \
    --batch_size 64 \
    --save_every 50 \
    --checkpoint_dir "$CHECKPOINT_DIR"

"""## 6. Write the sample-generation script (`ddpm_generate.py`)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ddpm_generate.py
# 
# import os
# import argparse
# import torch
# 
# from ddpm_model import DDPM, T, get_cosine_schedule, generate_fid_samples_ddim
# 
# 
# def generate(checkpoint_path, output_dir="samples", total_samples=10000,
#              batch_size=64, ddim_steps=500):
#     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#     print(f"Using device: {device}")
# 
#     model = DDPM().to(device)
# 
#     print(f"Loading checkpoint: {checkpoint_path}")
#     checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
# 
#     if "ema_model_state_dict" in checkpoint:
#         model.load_state_dict(checkpoint["ema_model_state_dict"])
#         print("Loaded EMA model weights.")
#     else:
#         model.load_state_dict(checkpoint["model_state_dict"])
#         print("Loaded standard model weights.")
#     model.eval()
# 
#     betas = get_cosine_schedule(T=T).to(device)
#     alphas = 1.0 - betas
#     alpha_bar = torch.cumprod(alphas, dim=0)
# 
#     print(f"Generating {total_samples} samples with DDIM ({ddim_steps} steps)...")
#     os.makedirs(output_dir, exist_ok=True)
#     generate_fid_samples_ddim(
#         model=model,
#         alpha_bar=alpha_bar,
#         device=device,
#         total_samples=total_samples,
#         batch_size=batch_size,
#         ddim_steps=ddim_steps,
#         output_dir=output_dir,
#     )
#     print(f"Done! Samples saved to '{output_dir}/'")
# 
# 
# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument("--epoch", type=int, required=True)
#     parser.add_argument("--checkpoint_dir", type=str, default="checkpoints")
#     parser.add_argument("--output_dir", type=str, default="samples")
#     parser.add_argument("--total_samples", type=int, default=10000)
#     parser.add_argument("--batch_size", type=int, default=64)
#     parser.add_argument("--ddim_steps", type=int, default=500)
#     args = parser.parse_args()
# 
#     ckpt_path = os.path.join(args.checkpoint_dir, f"ddpm_epoch_{args.epoch}.pt")
#     if os.path.exists(ckpt_path):
#         generate(
#             ckpt_path,
#             output_dir=args.output_dir,
#             total_samples=args.total_samples,
#             batch_size=args.batch_size,
#             ddim_steps=args.ddim_steps,
#         )
#     else:
#         print(f"Error: checkpoint not found at {ckpt_path}")
#

"""## 7. Generate samples from a checkpoint

Set `EPOCH` to a checkpoint you've already saved (e.g. `50`, `100`, ...). This uses the EMA weights and DDIM
sampling (500 steps by default, matching the training script's evaluation setting).
"""

EPOCH = 50  # change to whichever checkpoint epoch you want to sample from

!python ddpm_generate.py \
    --epoch $EPOCH \
    --checkpoint_dir "$CHECKPOINT_DIR" \
    --output_dir samples_epoch_$EPOCH \
    --total_samples 64 \
    --ddim_steps 500

"""### Preview a few generated samples"""

import glob
from PIL import Image
import matplotlib.pyplot as plt

sample_dir = f"samples_epoch_{EPOCH}"
paths = sorted(glob.glob(f"{sample_dir}/*.png"))[:16]

fig, axes = plt.subplots(4, 4, figsize=(8, 8))
for ax, p in zip(axes.flatten(), paths):
    ax.imshow(Image.open(p))
    ax.axis('off')
plt.tight_layout()
plt.show()

"""## 8. Write the FID evaluation script (`ddpm_evaluate.py`)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ddpm_evaluate.py
# 
# import os
# import sys
# import re
# from torch_fidelity import calculate_metrics
# 
# 
# def get_available_epochs():
#     """Scans the current directory for fake_images_epoch_X folders."""
#     epochs = []
#     pattern = re.compile(r"^fake_images_epoch_(\d+)$")
#     for item in os.listdir("."):
#         if os.path.isdir(item):
#             match = pattern.match(item)
#             if match:
#                 epochs.append(int(match.group(1)))
#     return sorted(epochs)
# 
# 
# def evaluate_single_epoch(epoch_num, min_images=10000):
#     fake_dir = f"fake_images_epoch_{epoch_num}"
#     print(f"\n Evaluating Epoch {epoch_num} (EMA weights)...")
# 
#     if not os.path.exists(fake_dir):
#         print(f"Error: '{fake_dir}' does not exist.")
#         return None
# 
#     images = [f for f in os.listdir(fake_dir) if f.lower().endswith((".png", ".jpg", ".jpeg"))]
#     num_images = len(images)
# 
#     if num_images < min_images:
#         print(f"Warning: Found {num_images}/{min_images} images. Skipping.")
#         return None
# 
#     try:
#         metrics = calculate_metrics(
#             input1="cifar10-train",
#             input2=fake_dir,
#             fid=True,
#             cuda=True,
#             batch_size=128,
#             verbose=False,
#         )
#         fid_score = metrics["frechet_inception_distance"]
#         print(f"Epoch {epoch_num} FID Score: {fid_score:.4f}")
#         return fid_score
#     except Exception as e:
#         print(f"Error during metrics calculation for Epoch {epoch_num}: {e}")
#         return None
# 
# 
# def main():
#     print("=" * 60)
#     print(" AUTOMATED DDPM EMA-FID EVALUATION")
#     print("=" * 60)
# 
#     fid_results = {}
# 
#     if len(sys.argv) >= 2:
#         epochs_to_test = [int(sys.argv[1])]
#     else:
#         epochs_to_test = get_available_epochs()
#         if not epochs_to_test:
#             print("No 'fake_images_epoch_X' folders found.")
#             sys.exit(1)
# 
#     for ep in epochs_to_test:
#         score = evaluate_single_epoch(ep)
#         if score is not None:
#             fid_results[ep] = score
# 
#     if fid_results:
#         print("\n" + "=" * 50)
#         print("FID EVOLUTION SUMMARY (EMA MODELS)")
#         print("-" * 50)
#         for ep in sorted(fid_results.keys()):
#             score = fid_results[ep]
#             if score < 10:
#                 status = " GOAL REACHED"
#             elif score < 20:
#                 status = " Excellent"
#             elif score < 50:
#                 status = " Good"
#             else:
#                 status = " Needs more training"
#             print(f"Epoch {ep:<9}{score:<20.4f}  {status}")
#         print("=" * 50)
# 
# 
# if __name__ == "__main__":
#     main()
#

"""## 9. Evaluate FID

Compares `fake_images_epoch_X` folders (auto-created during training every `--save_every` epochs) against the
real CIFAR-10 training distribution using `torch-fidelity`. Requires **10,000** images in the folder being
evaluated — the training script's default FID checkpoints generate fewer (64) for speed, so for a real FID
number, generate a full 10,000-image batch first:

```
!python ddpm_generate.py --epoch $EPOCH --checkpoint_dir "$CHECKPOINT_DIR" \
    --output_dir fake_images_epoch_$EPOCH --total_samples 10000 --ddim_steps 500
```

Then evaluate a specific epoch, or omit the argument to scan and evaluate every `fake_images_epoch_*` folder
found in the current directory.
"""

!python ddpm_evaluate.py $EPOCH
